version: '3'

services:
  influxdb:
    image: influxdb:2.7.4-alpine
    #        env_file:
    #            - influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influx-store:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    networks:
      - my-influx-network

volumes:
  influx-store:

networks:
  my-influx-network:
    driver: bridge